### ISSUE TITLE
RuntimeError: The content for this response was already consumed

### ISSUE THREAD

**Issue by M0rtalW0mbat** [tintoy/seqlog#1]
* PySeq version: 0.5.0
* Python version:  3.5.2 x64
* Operating System: Windows 10 x64
* seqlog version: 0.1.0
* Seq server version: 3.2.16

### Description
This simple example somethimes fire exception:

```
if __name__ == '__main__':
    seqlog.log_to_seq(
        server_url='http://192.168.121.21:5341',
        level=logging.INFO,
        batch_size=2,
        auto_flush_timeout=1000,
        override_root_logger=True
    )
    logging.error("Hello, {name}!", name="World")
    logging.error("Hello, {name}!", name="World1")
    logging.error("Hello, {name}!", name="World2")
    logging.error("Hello, {name}!", name="World3")
```
### Exception

```
Exception in thread Queue consumer (SeqLogHandler):
Traceback (most recent call last):
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\consumer.py", line 109, in _queue_processor
    self._add_to_current_batch(record)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\consumer.py", line 125, in _add_to_current_batch
    self.flush()
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\consumer.py", line 64, in flush
    self.callback(current_batch)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\structured_logging.py", line 286, in publish_log_batch
    response = self.session.post(self.server_url, json=request_body)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 628, in send
    r.content
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 750, in content
    'The content for this response was already consumed')
RuntimeError: The content for this response was already consumed
```

**Comment by tintoy** [comment]
Thanks for the detailed report! I'll have a look shortly :)

**Comment by tintoy** [comment]
Ok, I think I've found the problem - if I publish a new version do you have time to try it out?

**Comment by M0rtalW0mbat** [comment]
Yep, give me a couple of days

**Comment by M0rtalW0mbat** [comment]
https://pypi.python.org/pypi/seqlog/0.3.0

**Comment by M0rtalW0mbat** [comment]
Now its hard to repeat, but i got it, see on screenshot in attach. As you can see i use VSCode debugger for simulate this situation, maybe this is important....
![2016-11-17 14 58 06](https://cloud.githubusercontent.com/assets/2420529/20380761/9833cb66-acd6-11e6-8f4f-e05f9d9091cd.png)

**Comment by M0rtalW0mbat** [comment]
Hmm, when i run this script in cmd shell, some messages is lost, in seq srv i see only two of them.
![seqlog2](https://cloud.githubusercontent.com/assets/2420529/20381076/608c72ec-acd8-11e6-8256-74fb970ace15.PNG)
![seqlog1](https://cloud.githubusercontent.com/assets/2420529/20381077/608caea6-acd8-11e6-8eb0-198b6a4d55a3.PNG)

**Comment by M0rtalW0mbat** [comment]
Somethimes only one of them:
![seqlog3](https://cloud.githubusercontent.com/assets/2420529/20381173/d8861ab4-acd8-11e6-8970-0d14ede13f24.PNG)

**Comment by M0rtalW0mbat** [comment]
My test script:
[InstallationsProcessing.zip](https://github.com/tintoy/seqlog/files/596842/InstallationsProcessing.zip)

**Comment by tintoy** [comment]
Ok thanks - that gives me something to work with; I'll have a look at it first thing tomorrow.

Sorry for the inconvenience:-/

**Comment by tintoy** [comment]
Apparently this can also happen if server returns an empty response. I'll try your script when I get home.

**Comment by tintoy** [comment]
Ok, this is weird - I'm running your test script but I cannot reproduce the problem :-/
I've run it 15-20 times and it may pause occasionally while flushing the log but never seems to crash.

I'm on Python 3.4.4 on OSX, though, so I'll try running this on my Surface when I get home and see if that makes a difference...

Some log entries going missing, BTW, is usually because the process exits before the queue can be fully flushed. I added a sleep at the end of your script and all your log entries then show up.

I'll see if I can do something about those lost events though - losing log entries during a crash is kinda poor behaviour...

In the meanwhile, what if you just add a `sleep(1)` to the end of your test script. Do you still get the error?

**Comment by M0rtalW0mbat** [comment]
Ok, sleep solve message losing, but it is not related with Exception and original problem :)

**Comment by M0rtalW0mbat** [comment]
I try run script in VSCode debugger again twice and on second try i catch same situation like earlier.
![seqlog4](https://cloud.githubusercontent.com/assets/2420529/20385726/2a96053c-aceb-11e6-8207-4d02640b20ab.PNG)
![seqlog5](https://cloud.githubusercontent.com/assets/2420529/20385725/2a95b9d8-aceb-11e6-9d9f-405fa7ba5142.PNG)

**Comment by M0rtalW0mbat** [comment]
One more hint: i use VSCode debugger implemented by plugin(Python plugin by Don Jayamanne). I forgot to mention this earlier.
![seqlog6](https://cloud.githubusercontent.com/assets/2420529/20385862/bcba0c60-aceb-11e6-831d-7620555e3d51.PNG)

**Comment by tintoy** [comment]
No worries - I'm going to try this on my Windows machine when I get home tomorrow. Thanks for sticking with this, we'll work it out eventually :)

**Comment by M0rtalW0mbat** [comment]
Yep, good luck with this :)

**Comment by tintoy** [comment]
BTW, if you want to automatically flush log, you can do something like:

```python
import atexit
import logging

atexit.register(logging.shutdown) # Will flush and close all log handlers when the app exits
```

**Comment by M0rtalW0mbat** [comment]
```
D:\workspace\AnalyticsProcessing>python InstallationsProcessing.py
Seqlog version: 0.3.0
aaaaaaaaaa
bbbbbbbbbbbbbbb
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1882, in shutdown
    h.close()
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\structured_logging.py", line 332, in close
    self.consumer.stop()
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python35\lib\site-packages\seqlog\consumer.py", line 90, in stop
    raise Exception("The consumer is not running.")
Exception: The consumer is not running.
```

**Comment by tintoy** [comment]
Cheers - found and fixed that bug already, just haven’t built a new package yet :)

**Comment by tintoy** [comment]
Ok - have tried the latest code on Windows and still can't reproduce the error:

![run test loop](https://cloud.githubusercontent.com/assets/1646284/20403984/16c60810-ad57-11e6-80f3-5027221dc751.jpg)

**Comment by tintoy** [comment]
It works from VS Code, too:

![image](https://cloud.githubusercontent.com/assets/1646284/20404413/f257202a-ad58-11e6-86c5-4d7f4bf208d2.png)

I'm going to try publishing a new package with all the changes I made yesterday and today, let's see if that makes a difference for you.

**Comment by tintoy** [comment]
Hi - could you give [v0.3.2](https://pypi.python.org/pypi/seqlog/0.3.2) a try?

**Comment by M0rtalW0mbat** [comment]
> When you run it from VS Code, are you running it with the debugger attached, or just using VS Code to launch it?
Yes, Im just using VS Code, but without breakpoints its don't crash. Breakpoints is very important :)

**Comment by tintoy** [comment]
Interesting - I did set breakpoints but only in the seqlog code. Where did you set yours again? Sorry on mobile so images not coming through...

**Comment by M0rtalW0mbat** [comment]
first: seqlog.set_global_log_properties(Application='13')
second: print('aaaaaaaaaa')
third: print('bbbbbbbbbbbbbbb')

**Comment by M0rtalW0mbat** [comment]
Script crush after third breakpoint in most cases

**Comment by tintoy** [comment]
Ok! I've managed to reproduce the problem (seems to only happen on VS Code in Windows) - I'll have a poke-around and see what I can find.

**Comment by M0rtalW0mbat** [comment]
> seems to only happen on VS Code in Windows

Im lucky :)

**Comment by M0rtalW0mbat** [comment]
Looks good, i can't reproduce crash on version 0.3.3. I think we can close this issue. Great job! :)

**Comment by tintoy** [comment]
Glad to hear it :)
