### ISSUE TITLE
post throws exception in version 0.3.11

### ISSUE THREAD

**Issue by gilzig** [tintoy/seqlog#17]
* PySeq version: 0.3.11
* Python version: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
* Operating System: windows 10

### Description
Basic operation does not work: After initializing the seqlog, I try to output something to the logger, and an exception occurs a few seconds later when it actually tries to post the message.
After some investigations, I installed an older version (0.3.10) and everything worked fine!

### What I Did
```
    seqlog.log_to_seq(
        server_url='http://localhost:5341',
        # api_key="My API Key",
        level=logging.INFO,
        batch_size=10,
        auto_flush_timeout=10,  # seconds
        override_root_logger=True,
        # json_encoder_class=json.encoder.JSONEncoder  
        )
   logging.info("Hello, {name}!", name="World")
```
The traceback is:
```
Traceback (most recent call last):
  File "C:\Users\gzigelman\AppData\Roaming\Python\Python36\site-packages\seqlog\structured_logging.py", line 372, in publish_log_batch
    response.raise_for_status()
  File "C:\Users\gzigelman\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5341/api/events/raw
Call stack:
  File "C:\Users\gzigelman\AppData\Local\Continuum\anaconda3\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\gzigelman\AppData\Local\Continuum\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\gzigelman\AppData\Local\Continuum\anaconda3\lib\threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\gzigelman\AppData\Roaming\Python\Python36\site-packages\seqlog\consumer.py", line 67, in flush
    self.callback(current_batch)
  File "C:\Users\gzigelman\AppData\Roaming\Python\Python36\site-packages\seqlog\structured_logging.py", line 375, in publish_log_batch
    self.handleError(batch[0])
Message: 'Hello, {name}!'
Arguments: ()
```
Currently I am able to use the older version, but it would be great to understand if I missed something...

Thank you very much!!
Gil

**Comment by tintoy** [comment]
Hmm, that's strange. What version of the Seq server are you using?

Can you try pasting the following into `testharness.py` and running it:

```python
#!/usr/bin/env python3

import logging
import socket
import os
from time import sleep

import seqlog

server_url = http://localhost:5341/"
api_key = "MY_API_KEY" # If you are using API keys

print("Logging to Seq server '{}' (API key = '{}').".format(server_url, api_key))

seqlog.log_to_seq(
    server_url,
    api_key,
    level=logging.INFO,
    auto_flush_timeout=0.2,
    additional_handlers=[logging.StreamHandler()],
    override_root_logger=True
)

print("Running...")

logging.info("Hi, {name}. {greeting}", name="Root logger", greeting="Nice to meet you")

logger1 = logging.getLogger("A")
logger1.info("Hi, {name}! {greeting}", name="world", greeting="Nice to meet you")

logger2 = logging.getLogger("A.B")
logger2.info("Bye, {name}! {greeting}", name="moon", greeting="Nice to meet you")

logger3 = logging.getLogger("C")
logger3.info("By, %s!", "moon")

print("Sleeping...")
sleep(0.5)
print("Done.")
```

**Comment by tintoy** [comment]
Also, can you have a look at `http://your-seq-server:5341/api/diagnostics/ingestion` to see if any errors are logged?

BTW, The only change between v0.3.10 and v0.3.11 is how the JSON encoder is configured (when configuring logging from a `dict` or configuration file). I suppose it's possible that this could be responsible, but I'm not sure how yet...

**Comment by gilzig** [comment]
Thank you for all the suggestions.
I tried running the sample code  - and it works...

http://localhost/api/diagnostics/ingestion shows:

> 2018-11-16 20:45:18 The ingestion API is configured and accepting requests

So it doesn't seem like too much related info is there...

I am running seq server as a docker image (datalust/seq:latest)

The complete code being run has some more logic, which might cause some conflict, though it shouldn't (for example. I use Flask for API interface)
I will try to move as much as I can to the sample you provided, and see when it breaks.
It is getting late here, so I will manage to do this only  tomorrow or Sunday.
I will let you know what I find.
Thank you very much!!
Gil

**Comment by gilzig** [comment]
Hi,

After a fresh check in the morning, I see that I used the 0.3.10 in my test last night, and this is why it worked...
When updating to 0.3.11 this morning, your sample code fails as well.
Where are the log files located in the docker image? (instead of the 'C:\ProgramData\Seq\Logs')?

Any more information I can provide?

Thanks,
Gil

**Comment by gilzig** [comment]
Just a little more info:
the call that throws the exception is:
            response = self.session.post(
                self.server_url,
                data=request_body_json,
                stream=True  # prevent '362'
            )
The values that I get are:

self.server_url is:

> http://localhost:5341/api/events/raw

request_body_json is:

> {"Events": [{"Timestamp": "2018-11-17 09:05:47.256725+02:00", "Level": "INFO", "MessageTemplate": "Hi, {name}. {greeting}", "Properties": {"MachineName": "IL-GZigelman", "ProcessId": 17860, "LoggerName": "root", "name": "Root logger", "greeting": "Nice to meet you", "ThreadId": 20616, "ThreadName": "MainThread"}}, {"Timestamp": "2018-11-17 09:05:47.256725+02:00", "Level": "INFO", "MessageTemplate": "Hi, {name}! {greeting}", "Properties": {"MachineName": "IL-GZigelman", "ProcessId": 17860, "LoggerName": "A", "name": "world", "greeting": "Nice to meet you", "ThreadId": 20616, "ThreadName": "MainThread"}}, {"Timestamp": "2018-11-17 09:05:47.256725+02:00", "Level": "INFO", "MessageTemplate": "Bye, {name}! {greeting}", "Properties": {"MachineName": "IL-GZigelman", "ProcessId": 17860, "LoggerName": "A.B", "name": "moon", "greeting": "Nice to meet you", "ThreadId": 20616, "ThreadName": "MainThread"}}, {"Timestamp": "2018-11-17 09:05:47.256725+02:00", "Level": "INFO", "MessageTemplate": "By, moon!", "Properties": {"MachineName": "IL-GZigelman", "ProcessId": 17860, "LoggerName": "C", "0": "moon"}}]}

**Comment by tintoy** [comment]
Hmm, not sure - I've never run Seq in Docker before; /var/log perhaps?

**Comment by tintoy** [comment]
One thing you could try is maybe running fiddler as a proxy to inspect the response?

**Comment by tintoy** [comment]
Ah, logs are in /data.

**Comment by tintoy** [comment]
Other options for troubleshooting:

https://docs.getseq.net/docs/ingestion-troubleshooting

**Comment by gilzig** [comment]
Thanks!
The log is updated after each run with the following error:

> {"@t":"2018-11-18T06:10:09.6170577Z","@mt":"HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms","@r":["0.6036"],"@l":"Error","@x":"System.NullReferenceException: Object reference not set to an instance of an object.\n   at Seq.Server.Web.Api.RawEventsController.TryParseBody(ApiKey apiKey, StorageEventCreationData[]& events, String& errorMessage)\n   at Seq.Server.Web.Api.RawEventsController.Ingest()\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\n   at Seq.Server.Web.Middleware.WebSocketAcceptMiddleware.Invoke(HttpContext context)\n   at Seq.Server.Web.Middleware.RequestAuthenticationMiddleware.Invoke(HttpContext httpContext)\n   at Seq.Server.Web.Middleware.BrowserSecurityOptionsMiddleware.Invoke(HttpContext context)\n   at Seq.Server.Web.Middleware.RequestCompletionMiddleware.Invoke(HttpContext httpContext)","RequestMethod":"POST","RequestPath":"/api/events/raw","StatusCode":500,"Elapsed":0.6036,"ErrorToken":"b2c14ff04fbc42348e951aec12f7f637","RequestProtocol":"HTTP/1.1","RequestHost":"localhost:5341","RequestHeaders":{"User-Agent":"python-requests/2.18.4","Content-Length":"1103"},"SourceContext":"Seq.Server.Web.Middleware.RequestCompletionMiddleware","RequestId":"0HLIC0HN27AR5:00000001","CorrelationId":null,"ConnectionId":"0HLIC0HN27AR5"}

I hope this can help,
Best,
Gil

**Comment by tintoy** [comment]
Hi - I'll open an issue in the Seq repository and see what they have to say. Do you know exactly what version of Seq you're running (they'll probably ask)? You can probably find out by running `docker logs <seq-container-name-or-id>`.

**Comment by gilzig** [comment]
Thanks so much!
The complete text of the logs is as follows:
  

> Seq ♦ Machine data, for humans.
> ─────────── © 2018 Datalust Pty Ltd ────
> 
> Running as server; press Ctrl+C to exit.
> 
> [07:34:27 INF] Seq "5.0.2287" running on OS "Linux 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018"
> [07:34:28 INF] Seq listening on ["http://localhost/", "http://localhost:5341/"]
> [07:34:28 INF] Opening document store "/data/Documents/documents.lmdb"
> [07:34:28 INF] Opening event store at "/data/Extents"
> [07:34:28 INF] Available storage engines in order of preference are ["FLARE"]
> [07:34:29 INF] Cache warm-up is required
> [07:34:29 INF] Initial memory cache warm-up "completed" in 119.1269 ms
> [07:34:29 INF] 168 segments warmed up ({"Schemata": 3, "Strings": 6})
> [07:34:29 INF] Storage subsystem available
> [07:44:29 INF] Applying 1 retention policies
> [07:44:29 INF] Removing all events before "2018-11-17T07:40:00.0000000Z" under policy "retentionpolicy-34"
> [07:44:29 INF] Retention policy progressed in 20.1984 ms (headway: null×), will resume from "2018-11-17T07:40:00.0000000Z"
> [07:44:29 INF] Retention processing and compaction took 141.1113 ms; allocating 599858.8887 ms for indexing
> [07:44:29 INF] Beginning indexing
> [07:44:29 INF] Wrote 0 index sets in 69 ms
> [07:44:29 INF] Indexing took 73 ms; total iteration time was 214.3831 ms
> [07:50:20 INF] Termination signal received
> [07:50:20 INF] Signalling for 3 worker task(s) to complete
> [07:50:24 INF] Stopping 12 scheduled tasks
> [07:50:24 INF] Stopping broadcast channel
> [07:50:24 INF] Closing event store
> [07:50:24 INF] Closing document store
> [07:50:24 INF] Server stopped cleanly
> ────────────────────────────────────────
>   Seq ♦ Machine data, for humans.
> ─────────── © 2018 Datalust Pty Ltd ────
> 
> Running as server; press Ctrl+C to exit.
> 
> [07:57:29 INF] Seq "5.0.2287" running on OS "Linux 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018"
> [07:57:31 INF] Seq listening on ["http://localhost/", "http://localhost:5341/"]
> [07:57:31 INF] Opening document store "/data/Documents/documents.lmdb"
> [07:57:31 INF] Opening event store at "/data/Extents"
> [07:57:31 INF] Available storage engines in order of preference are ["FLARE"]
> [07:57:32 INF] Storage subsystem available
> [07:57:33 INF] Cache warm-up is required
> [07:57:33 INF] Initial memory cache warm-up "completed" in 268.1582 ms
> [07:57:33 INF] 168 segments warmed up ({"Schemata": 79, "Strings": 552})

**Comment by thatshane** [comment]
Hi,

I'm receiving the same error as the above user. For me this seemed to be an issue with using Seq 5.0 which was just released in the last few days With 4.2 I was able to publish logs fine with seqlog v0.3.11. @tintoy have you been able to use the library successfully with an instance of Seq 5.0?

Thanks :)

**Comment by tintoy** [comment]
Interesting! No, I've not tried Seq 5.0 (only have a license for 4.x). I'll have chat to the Seq folks shortly to see if it's a known issue.

**Comment by tintoy** [comment]
I've [submitted a support question](https://docs.getseq.net/discuss/5bf300725faec3000e561fa6), so we'll see what they have to say :)

**Comment by gilzig** [comment]
The strange thing is that if I copy the message Url and Body and Post it in an external application like Postman, it is successful. 
But let's wait and see :)

**Comment by tintoy** [comment]
Ok, [it turns out](https://github.com/datalust/seq-tickets/issues/756) Seq 5.x was expecting there to be a `Content-Type` header, which Seqlog wasn't supplying. It'll be fixed in the next build of Seq, but I'm also going to put out a new release of Seqlog which fixes the problem, too.

**Comment by tintoy** [comment]
Closing, feel free to reopen if the problem occurs again :)
