### ISSUE TITLE
Can seqlog be used to push structured logs to logstash?

### ISSUE THREAD

**Issue by gilzig** [tintoy/seqlog#19]
### Description

I have just learnt that the licensing terms of Seq might not be good for the product I am developing(I might need to purchase a separate license per installation), and I am checking alternatives.
One of the alternatives is using ELK (Logstash + Elasticsearch + Kibana).
My Python code already uses seqlog and I am very happy with the structured logging capabilities I have. Do you know if there is an easy way to use seqlog to push the json structure to logstash (or directly to elasticsearch)?

Thank you very much!
Gil

**Comment by tintoy** [comment]
Hi - it’s not designed to support other log servers but could certainly be modified to do so.

Seqlog is MIT-licensed and I’m more than happy for the code to be reused if you know someone who could adapt it to whatever format your log server of choice is.

Work’s a little crazy at the moment so I don’t really have the time to modify it myself but I’m happy to offer advice to anyone who’s keen to do so :)

**Comment by tintoy** [comment]
You can probably get away with just creating a custom log handler (copy the code from `SeqLogHandler`).

**Comment by Vacant0mens** [comment]
As tintoy said, you can create a custom `Handler` class (you can read more [here](https://docs.python.org/3/library/logging.handlers.html) )

Alternatively, a quick search shows at least four modules on PyPi (that can be installed with `pip`).
[python-elastic-logstash](https://pypi.org/project/python-elastic-logstash/) seems to be the most supported/up-to-date

But there's also [python-logstash-async](https://pypi.org/project/python-logstash-async/) if your use case calls for asynchronous calls.

Both of those modules are integrations to python's official `logging` module via `Handler`'s. So all that'd be needed is to add the module to your code, and then add a handler to your current logging config (which you can read about [here](https://docs.python.org/3/library/logging.config.html) )
