### ISSUE TITLE
Missing log not logged and not flushed

### ISSUE THREAD

**Issue by arisliang** [tintoy/seqlog#28]
* PySeq version: 0.3.17
* Python version: 3.7.7
* Operating System: Windows 10

### Description

There're missing logs, and flush does not seem always work to push them.

Say I have a few logs, and many times only first few logs being logged, last few did not get through, even if I added flush at the end, it didn't flush it.

I expect all logs are being sent and logged, and flush should send them over in case there're some logs still in the buffer.

**Comment by arisliang** [comment]
I know what's wrong now. `auto_flush_timeout` should be in seconds.

>auto_flush_timeout=10,  # seconds

**Comment by tintoy** [comment]
Hi - thanks, I’ll see if I can draw attention to that in the docs :)
