### ISSUE TITLE
seqlog is still using travis-ci.org

### ISSUE THREAD

**Issue by piotrmaslanka** [tintoy/seqlog#34]
As you may know, travis-ci.org has retired and now a page called travis-ci.com is available.

To migrate your projects you need to:
1. Make an account
2. Select a plan (this is very important)
3. Enable development version
4. Migrate the project proper.

Good luck, @tintoy !

**Comment by tintoy** [comment]
Thanks! Up and running again 🙂 

I'll make a separate issue for migrating to Python 3.8.
