### ISSUE TITLE
Migrate tests to Python 3.8

### ISSUE THREAD

**Issue by tintoy** [tintoy/seqlog#38]
As suggested by @piotrmaslanka, this will probably make it a little easier to build / test (since 3.8 has more wheels available for it, and may also mitigate some threading-related issues arising from idiosyncratic usage of the threading API).

**Comment by Vacant0mens** [comment]
I would say upgrading to 3.10 would be even better, if it's possible.
[This build](https://github.com/tintoy/seqlog/runs/10792275090) isn't working on 3.6, but it worked locally when I ran it locally using 3.10.

**Comment by tintoy** [comment]
Thanks for your patience, and sorry for the delay!

Published [v0.3.23](https://pypi.org/project/seqlog/0.3.23/) 🙂

**Comment by Vacant0mens** [comment]
This seems like it could be closed, yes?

**Comment by tintoy** [comment]
Yep! Thanks for the reminder 🙂
