### ISSUE TITLE
Add tests for configure_from_file / configure_from_dict

### ISSUE THREAD

**Issue by tintoy** [tintoy/seqlog#5]

**Comment by Vacant0mens** [comment]
How in-depth should this be? 

Options:
1. make sure that those two methods don't break with a valid file/dict with a couple options set. OR
2. check that the handlers, formatters, loggers, (etc.) and all of their parameters get set/setup correctly. OR
3. somewhere in between the two

**Comment by tintoy** [comment]
I think maybe option 1 is highest priority (tests verify the schema / contract behaviour), and whatever time we have left over we can spend on 2 (tests verify that given config data results in expected config).

Does that sound reasonable?

**Comment by Vacant0mens** [comment]
Even though I've been using python for a while now, I'm not super familiar with pytest 😬 , but I think this might be a good base for testing the dictConfig?
https://github.com/tintoy/seqlog/commit/11df187c063b3fb7781c053f534834e04fe88dd0

**Comment by tintoy** [comment]
Nice find! Yeah that'd do the trick.

**Comment by piotrmaslanka** [comment]
I'll handle this [here](https://github.com/smok-serwis/seqlog/tree/issue-%235)
