### ISSUE TITLE
Can't pass a value for batch_size when Configuring logging from a dictionary.

### ISSUE THREAD

**Issue by DaveNankervis** [tintoy/seqlog#50]
I've explored the package and can't seem to find a way to pass the batch_size value.

**Comment by tintoy** [comment]
Sorry, I'm still at work; I'll try to have a look at this later tonight when I get home 🙂

**Comment by tintoy** [comment]
Sorry for the delay; work has been pretty full-on this week!

Have a look at https://github.com/tintoy/seqlog/blob/226a3af4434628b076e343ac62f3ce48ff054891/docs/usage-gunicorn.rst (see the bit about `api/logging_config.yml`).

**Comment by DaveNankervis** [comment]
@tintoy that's no problem at all! I appreciate your help. I ended up getting it to work after checking the link.

**Comment by DaveNankervis** [comment]
@tintoy that's no problem at all! I appreciate your help. I ended up getting it to work after checking the link.
