### ISSUE TITLE
LogRecord.getMessage does not parse msg to string, intentional?

### ISSUE THREAD

**Issue by Liquidmasl** [tintoy/seqlog#51]
hi there, I am currently trying to change our logging to use seqlog
but i am running into issues when the logged message is not a string per se, before we (or, better, i lib we use) logs dicts, or ints. Internally it was parsed to string 

in `LogRecord.getMessage()`  ` msg = str(self.msg)`

but in `StructuredLogRecord.getMessage()` this is not done!

I can make a custom class that derived from structured log record and overwrite the `getMessage()` method to do this, but that seams quite convoluted, and I am not sure if I break some inner workings. 

Additionally I noticed that when args are provided, log props are not filled in?

**Comment by Liquidmasl** [comment]
I fixed it for me by overwriting `makeRecord()`

```py
    def makeRecord(self, name, level, fn, lno, msg, args, exc_info, func=None, extra=None, sinfo=None):
        msg = str(msg)
        return super().makeRecord(name, level, fn, lno, msg, args, exc_info, func, extra, sinfo)
```

But I think casting to string in your code should pose no problem because everything in that method kinda wants a string anyway. 
Maybe ima do my first open source pull request 😅

**Comment by tintoy** [comment]
Could even do a quick type check in there as well but yeah feel free to create a PR 🙂

**Comment by tintoy** [comment]
BTW, one thing to be think about is that if the string representation of an object looks too much like a string with `{format} {holes}` then that may still have the potential to cause problems somewhere down the line.

**Comment by tintoy** [comment]
Hi - I finally got the chance to have a proper read of [the logging documentation](https://docs.python.org/3/library/logging.html#logging.debug) and it looks like `msg` is declared as a message-format string (i.e. always a interpreted as string).

It sounds like your override would work for what you are trying to do but I'd be hesitant to change `seqlog`'s default behaviour since it would no longer line up with the logging specification.

I'm happy to accept a PR for the docs though if you'd like to add info about how to handle situations like yours (eg. the workaround you figured out above) 🙂

**Comment by Liquidmasl** [comment]
> hesitant to change seqlog's default behaviour since it would no longer line up with the logging specification

you mean with the structured logging specification or the default python logging specification? 
because the default `LogRecord` is dong this cast anyway! 

I will try to get this done! Honestly I have not done any PR for an open source project yet, so lets see if I can come around to that!
Thank you for your engagement in any case (:

**Comment by tintoy** [comment]
Yeah the python logging spec - I think the cast may look like undocumented behaviour if it's not in the docs

**Comment by tintoy** [comment]
Ok - have added it; will publish a release tomorrow (just need to do some testing this afternoon).

Thanks for reporting! 🙂

**Comment by Vacant0mens** [comment]
@Liquidmasl did tintoy's commit fix your issue?

**Comment by tintoy** [comment]
Apologies for not having published the package yet; I've been spending a lot of time fighting fires at work.

I'll get a new version of the package published sometime today.

**Comment by tintoy** [comment]
Published [v0.3.27](https://pypi.org/project/seqlog/0.3.27/) 🙂

**Comment by Vacant0mens** [comment]
merged and published. closing this issue. 
We can reopen it if this merge didn't fix the issue.

**Comment by Liquidmasl** [comment]
> @Liquidmasl did tintoy's commit fix your issue?

I am super sorry this got lost in my github notifications!

I am happy this change made it in, thank you !
