### ISSUE TITLE
Feature request: seq handler fallback, or error handling, or callback

### ISSUE THREAD

**Issue by Liquidmasl** [tintoy/seqlog#52]
When the seq server is not reachable for some reason, a LOT of stacktrace is written into the console
it would be nice if a fallback handler could be set and errors would be handled cleaner.

for example define a file handler as fallback, or nothing, or maybe a callback function that is called if something goes wrong!

**Comment by tintoy** [comment]
Hmm. There is a `set_callback_on_failure` function that you can call to register a handler but as for the console logging stuff I'll need to take a look and get back to you.

**Comment by tintoy** [comment]
I think we could safely suppress console logging of failed requests if a failed-request handler was already registered.

I'll see what I can do over the weekend 🙂

**Comment by Liquidmasl** [comment]
oh there is, i missed that, will look into that, thank you

**Comment by tintoy** [comment]
No problem - I'm not sure the docs actually mention it (I'll get them updated if they don't already).

**Comment by tintoy** [comment]
Docs for failure callback can be found [here](https://seqlog.readthedocs.io/en/latest/usage.html#callback-on-log-submission-failure).

I think this should now be resolved in the current version of the package (sorry for the delay, it's been a busy couple of weeks!) so I'm going to close this issue; please feel free to reopen it, though, if it's still not working for you 🙂
