### ISSUE TITLE
yaml package is missing from installation requirements

### ISSUE THREAD

**Issue by blint587** [tintoy/seqlog#6]
* PySeq version: 0.3.5, 0.3.6, 0.3.7, 0.3.8
* Python version: 3.5, 3.6

### Description

yaml package is missing from installation requirements and eventually throws a ModuleNotFoundError

**Comment by tintoy** [comment]
Ugh, sorry I thought I'd fixed that! Give me a minute and I'll have a look.

**Comment by tintoy** [comment]
Could you give v0.3.9 a try?

**Comment by blint587** [comment]
It seams OK, thanks for the quick response  :)

**Comment by tintoy** [comment]
No worries - sorry for the inconvenience :D
