### ISSUE TITLE
Type hint on set_global_log_properties

### ISSUE THREAD

**Issue by robin523790** [tintoy/seqlog#60]
* PySeq version: 0.3.28
* Python version: 3.11.3
* Operating System: Windows

### Description

NOTE: This is only a display error in PyCharm. Execution of the code works fine, and neither VSCode nor pylance nor pyright report any issues.

PyCharm reports a type error on `set_global_log_properties()`:

![image](https://github.com/tintoy/seqlog/assets/52233887/08ccfc6d-be65-4237-a532-ccd4d4d244ab)

This is because the type is defined as dict[str, dict] instead of dict[str, str] in the comment:

![image](https://github.com/tintoy/seqlog/assets/52233887/2d833721-c7b3-42c8-bf80-127161628b7b)

### Suggested solution

According to https://peps.python.org/pep-0484/#arbitrary-argument-lists-and-default-argument-values it should be OK to change the type to `str`... and in fact, the error goes away.

**Comment by tintoy** [comment]
Thanks for reporting! I'll get this done tomorrow morning 🙂

**Comment by tintoy** [comment]
Published [v0.3.29](https://pypi.org/project/seqlog/0.3.29/) 🙂

**Comment by Vacant0mens** [comment]
merged and published. closing this issue.
