### ISSUE TITLE
Feature request, hide errors caused by seq server unavailable

### ISSUE THREAD

**Issue by sustem** [tintoy/seqlog#61]
* PySeq version: 0.3.29
* Python version: 3.8
* Operating System: Windows

### Description

This is not a bug, it's a feature request.

Is there any way to hide log errors that are caused by the seq log server being unavailable?
This is currently stopping me from deploying this excellent logging. (i'm a .net developer currently using python..)

I cannot risk having lots of errors displayed to a user due to logging not working.

**Comment by tintoy** [comment]
Hi - I’ll see about adding a config switch to disable the errors (normally if logging isn’t working I’d want to know about it ASAP but I can Thai in some scenarios it would be too noisy).

**Comment by sustem** [comment]
Thanks!

In my case it's an application installed and running in many obscure
locations so I cannot guarantee that they reach my logserver.

Regards,
Stefan

**Comment by tintoy** [comment]
Published [v0.3.30](https://pypi.org/project/seqlog/0.3.30/) (sorry for the delay, I'd completely forgotten about this one).

**Comment by Vacant0mens** [comment]
merged and published. closing this issue.
