### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by piotrmaslanka** [tintoy/seqlog#75]
The docs at readthedocs:
![image](https://github.com/user-attachments/assets/68613d0d-d38c-4a9a-adb8-6565e36b67d2)

The docs I just built:
![image](https://github.com/user-attachments/assets/f333008b-682f-444f-ad37-2fb178acaa35)

Please find out what goes wrong, since I don't really have access to your readthedocs account.
Please also report why readthedocs fails to build our docs anymore.

**Comment by tintoy** [comment]
Thanks - I can’t remember how their build is meant to work; will take a look tomorrow.

**Comment by tintoy** [comment]
Sorry, production issues at work last 2 days - hoping o get to this today 🙂

**Comment by tintoy** [comment]
I've triggered a rebuild of the docs, and invited you to the project on ReadTheDocs. Does this look correct?

https://seqlog.readthedocs.io/en/latest/

**Comment by piotrmaslanka** [comment]
@tintoy you can set up readthedocs to build the documentatioon each time a commit to master is made.
![image](https://github.com/user-attachments/assets/b4c19094-cef6-405e-a039-86d1090c029c)
I'd do so, but I have no permissions.

**Comment by tintoy** [comment]
Cheers - will set that up this weekend :)
